version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  publish_service:
    build:
      context: .
      dockerfile: Dockerfile.publish
    container_name: publish_service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  consume_service:
    build:
      context: .
      dockerfile: Dockerfile.consume
    container_name: consume_service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka
